owner: dhtoan
repo: uptime

sites:
  - name: Doligo
    url: https://www.doligo.net

status-website:
  cname: up.doligo.net
  logoUrl: https://www.doligo.net/wp-content/uploads/assets/images/logo.png
  name: Doligo
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
